# -*- coding: utf-8 -*-
"""Exercícios PDS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CVnnICjBddZULgNMsY7ajkW5Uxs7yRC9
"""

import statistics
import math
import numpy as np


empresa4 = [1400,1750,2000,4500,5900]
media = sum(empresa4) / len(empresa4)
print(f'Média: {media}')


moda = statistics.mode(empresa4)
print(f"Moda: {moda}")

empresa4.sort()
n = len(empresa4)
mediana = (empresa4[n//2] if n % 2 != 0 else (empresa4[n//2 - 1] + empresa4[n//2]) / 2)
print(f"Mediana: {mediana}")


variancia = np.var(empresa4)
print(f"Variância: {variancia}")

desvio_padrao = sum(empresa4) / len(empresa4)
desvio_padrao = math.sqrt(variancia)
print(f"Desvio Padrão: {desvio_padrao}")